package com.sagisawa.gbfaccelerator.cert

import android.content.ContentValues
import android.content.Context
import android.content.Intent
import android.os.Build
import android.os.Environment
import android.provider.MediaStore
import android.provider.Settings
import android.security.KeyChain
import java.io.File
import java.io.InputStream
import java.security.KeyStore
import java.security.MessageDigest
import java.security.cert.CertificateFactory
import java.security.cert.X509Certificate
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

/**
 * Management and diagnostic utilities for GBF-Accelerator's Root CA Certificate.
 *
 * Handles detection of the local CA cert file (generated by Go Core into `certs/ca.crt`),
 * inspection of validity & SHA-256 fingerprint, installation via KeyChain intent,
 * export to Downloads for Android 11+ manual security settings import,
 * and detection of system trust status.
 */
object CaCertManager {

    const val CERT_FILE_NAME = "ca.crt"
    const val CERTS_DIR_NAME = "certs"
    const val EXPORT_DISPLAY_NAME = "gbf_ca.crt"
    const val DEFAULT_ALIAS = "GBF-Accelerator-CA"
    const val CA_ISSUER_KEYWORD = "GBF Local Accelerator"

    data class CertInfo(
        val exists: Boolean,
        val subject: String = "",
        val issuer: String = "",
        val sha256Fingerprint: String = "",
        val validFrom: String = "",
        val validUntil: String = "",
        val isExpired: Boolean = false,
        val isTrustedInSystem: Boolean = false,
        val fileSizeBytes: Long = 0L,
        val filePath: String = ""
    )

    fun getCaCertFile(context: Context): File {
        return File(File(context.filesDir, CERTS_DIR_NAME), CERT_FILE_NAME)
    }

    fun parseCertificate(inputStream: InputStream): X509Certificate {
        val certFactory = CertificateFactory.getInstance("X.509")
        return certFactory.generateCertificate(inputStream) as X509Certificate
    }

    fun calculateSha256Fingerprint(cert: X509Certificate): String {
        val digest = MessageDigest.getInstance("SHA-256").digest(cert.encoded)
        return digest.joinToString(":") { "%02X".format(it) }
    }

    fun getCertInfo(context: Context): CertInfo {
        val file = getCaCertFile(context)
        return getCertInfoFromFile(file)
    }

    fun getCertInfoFromFile(file: File): CertInfo {
        if (!file.exists() || file.length() == 0L) {
            return CertInfo(exists = false)
        }

        return try {
            val cert = file.inputStream().use { parseCertificate(it) }
            val now = Date()
            val dateFormat = SimpleDateFormat("yyyy-MM-dd HH:mm:ss", Locale.US)
            val sha256 = calculateSha256Fingerprint(cert)
            val trusted = isCaInstalledInSystem(sha256)

            CertInfo(
                exists = true,
                subject = cert.subjectX500Principal.name,
                issuer = cert.issuerX500Principal.name,
                sha256Fingerprint = sha256,
                validFrom = dateFormat.format(cert.notBefore),
                validUntil = dateFormat.format(cert.notAfter),
                isExpired = now.before(cert.notBefore) || now.after(cert.notAfter),
                isTrustedInSystem = trusted,
                fileSizeBytes = file.length(),
                filePath = file.absolutePath
            )
        } catch (_: Throwable) {
            CertInfo(
                exists = true,
                filePath = file.absolutePath,
                fileSizeBytes = file.length()
            )
        }
    }

    fun isCaInstalledInSystem(expectedFingerprint: String = ""): Boolean {
        return try {
            val ks = KeyStore.getInstance("AndroidCAStore")
            ks.load(null)
            val aliases = ks.aliases()
            while (aliases.hasMoreElements()) {
                val alias = aliases.nextElement()
                val cert = ks.getCertificate(alias) as? X509Certificate ?: continue
                if (expectedFingerprint.isNotEmpty()) {
                    val fp = calculateSha256Fingerprint(cert)
                    if (fp.equals(expectedFingerprint, ignoreCase = true)) {
                        return true
                    }
                }
                if (cert.issuerX500Principal.name.contains(CA_ISSUER_KEYWORD)) {
                    return true
                }
            }
            false
        } catch (_: Throwable) {
            // AndroidCAStore unavailable in unit test or restricted sandbox
            false
        }
    }

    fun createInstallIntent(context: Context): Intent? {
        val file = getCaCertFile(context)
        if (!file.exists()) return null
        val bytes = file.readBytes()
        return KeyChain.createInstallIntent().apply {
            putExtra(KeyChain.EXTRA_CERTIFICATE, bytes)
            putExtra(KeyChain.EXTRA_NAME, DEFAULT_ALIAS)
        }
    }

    fun createSecuritySettingsIntent(): Intent {
        return Intent(Settings.ACTION_SECURITY_SETTINGS)
    }

    fun exportCaCertToDownloads(context: Context): Pair<Boolean, String> {
        val src = getCaCertFile(context)
        if (!src.exists()) {
            return Pair(false, "CA certificate file does not exist yet. Please start Go Core first.")
        }

        return try {
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
                val contentValues = ContentValues().apply {
                    put(MediaStore.MediaColumns.DISPLAY_NAME, EXPORT_DISPLAY_NAME)
                    put(MediaStore.MediaColumns.MIME_TYPE, "application/x-x509-ca-cert")
                    put(MediaStore.MediaColumns.RELATIVE_PATH, Environment.DIRECTORY_DOWNLOADS)
                }
                val uri = context.contentResolver.insert(MediaStore.Downloads.EXTERNAL_CONTENT_URI, contentValues)
                if (uri != null) {
                    context.contentResolver.openOutputStream(uri)?.use { out ->
                        src.inputStream().use { inp -> inp.copyTo(out) }
                    }
                    Pair(true, "已成功导出至【下载】目录 (${EXPORT_DISPLAY_NAME})")
                } else {
                    exportFallback(context, src)
                }
            } else {
                @Suppress("DEPRECATION")
                val targetDir = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS)
                if (!targetDir.exists()) targetDir.mkdirs()
                val target = File(targetDir, EXPORT_DISPLAY_NAME)
                src.copyTo(target, overwrite = true)
                Pair(true, "已导出至: ${target.absolutePath}")
            }
        } catch (e: Throwable) {
            exportFallback(context, src)
        }
    }

    private fun exportFallback(context: Context, src: File): Pair<Boolean, String> {
        return try {
            val fallbackDir = context.getExternalFilesDir(Environment.DIRECTORY_DOWNLOADS) ?: context.filesDir
            val target = File(fallbackDir, EXPORT_DISPLAY_NAME)
            src.copyTo(target, overwrite = true)
            Pair(true, "已导出至应用私有目录: ${target.absolutePath}")
        } catch (t: Throwable) {
            Pair(false, "导出失败: ${t.message}")
        }
    }
}
